# Miyadaiku config file

# Base URL of the site
site_url: https://32imuf.com/

# Title of the site
site_title: 32imuf.com

# Default language code
lang: ja-JP

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

# デフォルトは未公開状態にする
draft: true
