# Miyadaiku config file

# Base URL of the site
site_url: http://localhost:8888/

# Title of the site
site_title: サイトの名前だよ

# Default language code
lang: ja-JP

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

# List of site theme
themes:
  - miyadaiku.themes.sample.blog

# デフォルトは未公開状態にする
draft: true
